// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iakypzxucnwtyhyhvgtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlha3lwenh1Y253dHloeWh2Z3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzQ1NjQsImV4cCI6MjA3Mzk1MDU2NH0.MTBjP0p9oA1_0RUBCmxyDrcEyViVXRj7qGTmNl8XXrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});